Implements MQTT java Implementation
genexuslabs/mqtt-external-object pull request #2
Opened 2022-05-10 16:47 UTC by iroqueta

Issue: 86328

2022-05-10 16:52 UTC, sebagomez commented
Pero mirá la notificación que me llega! Yo te lo aprobaba de ojos cerrado Roquet, pero vamos a ver qué dice José :D

Abrazo!

2022-05-17 15:05 UTC, jechague requested changes
Please, delete the binary files (zip and xpz) from the repo and add them to the release you'll create later.

Sry for the delay in reviewing this 🙇‍♂️

2022-05-17 15:06 UTC, jechague commented
> Pero mirá la notificación que me llega! Yo te lo aprobaba de ojos cerrado Roquet, pero vamos a ver qué dice José :D
> 
> Abrazo!

👋

2022-05-17 15:21 UTC, jechague approved these changes
Tks for the changes!

LGTM

2022-05-17 15:22 UTC, merged